services:
  news:
    image: jogyoungjun/news:latest
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:mysql://news_mysql:3306/news?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_PASSWORD: root_password
    ports:
      - "8400:8080"
    depends_on:
      user_mysql:
        condition: service_healthy

  news_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: news
    ports:
      - "3400:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
